version: '3'

services:
  # Rails application service
  web:
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: open_flights_production
      POSTGRES_USER: open_flights
      POSTGRES_PASSWORD: <%= ENV['OPEN_FLIGHTS_DATABASE_PASSWORD'] %>
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
